### ISSUE TITLE
rename json.c/h

### ISSUE THREAD

**Issue by aleks-f** [skeeto/pdjson#11]
@skeeto small request: rename json.c/h to `pdjson` or `pd_json`.

we have a name conflict - json is a pretty common name; renaming it would make it easier to simply copy/paste files without any renaming. not a huge deal, but would be nice; if you don't mind, I'll send a pull

**Comment by skeeto** [comment]
I too was thinking about this just yesterday while fixing that bug. 
Since I wanted to follow it up with some unit tests (96041f7), I just 
did it myself. I settled on pdjson.c/pdjson.h but left all the API 
identifiers alone. The unit tests will help to avoid a repeat of #10.

**Comment by aleks-f** [comment]
thank you @skeeto !
