### ISSUE TITLE
Would you consider C90 support?

### ISSUE THREAD

**Issue by ellio167** [skeeto/pdjson#17]
I need a C90 json library and this is so close.  Would you consider accepting the changes necessary to make this C90 compliant?

It seems that the biggest change would be related to the `json_error` macro, which would need to become a function instead.

**Comment by skeeto** [comment]
Take a look at the "strict-ansi" branch. It's tidied up and restricted 
to plain old C89/C90. Though note the API is a bit different (and 
simpler).

**Comment by ellio167** [comment]
Great!  I didn't notice that previously.  I'll try it out.
