### ISSUE TITLE
Error strings include "error" phrase, line number

### ISSUE THREAD

**Issue by boris-kolpackov** [skeeto/pdjson#20]
I was surprised to find that the error messages returned by `json_get_error()` all contain the `error: <line>:  ` prefix. To me this seems to go against the overall philosophy of the library which is to provide the information in its most elementary form. In this case the line can be easily obtained with `json_get_lineno()` and then incorporated into diagnostics in the desired form (for example, I prefer the more traditional `<file>:<line>: error: <message>` format).

I am willing to do the work to fix this but would like to discuss the best approach. I am not sure that just dropping this prefix would be acceptable since existing code may by now rely on it being there.

Other, more elaborate options include having a flag, either a compile-time macro or a run-time flag (similar to existing `JSON_FLAG_*`).

Another option would be to have another function that returns a pointer to the "tail" of the existing strings without the prefix (this is, in fact, pretty much what I am doing now as a workaround). This would be pretty easy to implement with the only drawback being the potentially unnecessary work done formatting the line number. But perhaps it's ok since this only happens in case of an error?

What do you think?

**Comment by skeeto** [comment]
I agree with you, and I'm fine with just removing the prefix without any 
workarounds. Programs really shouldn't depend on anything particular 
about the string contents. I just did this now.

It might be worth working out a small, fixed set of symbolic names for 
the various error conditions. Programs can then choose to ignore the 
string messages and use the symbol  to choose from their own strings. 
For example: JSON_ERROR_INVALID_BYTE, JSON_ERROR_EXPECTED_COMMA, 
JSON_ERROR_OOM, etc.
