### ISSUE TITLE
Use RFC8259 terminology in error messages

### ISSUE THREAD

**Issue by boris-kolpackov** [skeeto/pdjson#21]
While I think the existing error messages are pretty good and self-consistent, they don't use the same terminology as what's in [RFC8259](https://tools.ietf.org/html/rfc8259). Probably the most representative example (and a sticking point to me) is "property name" vs "object member name".

Would there be interest in having this fixed? If so, I would be willing to do the work.

**Comment by skeeto** [comment]
Very good point, and I'd like this idea! I don't have any preference for 
the current use of non-standard terminology. Feel free to make a PR for 
it.
