### ISSUE TITLE
Don't print `EOF` in diagnostics

### ISSUE THREAD

**Issue by boris-kolpackov** [skeeto/pdjson#32]
Currently, if I attempt to parser JSON input text like `[2` or `fals` (without trailing newline), I get the following error string:

```
unexpected byte '�'
```

Or:

```
expected 'e' instead of byte '�'
```

Not sure if this considered acceptable. It wasn't for me, so I've fixed it in my fork. If interested, you can pull the fix from here: https://github.com/boris-kolpackov/pdjson/commit/5b0500c1f3868c3fb731374de257eab1aaa0829d

**Comment by skeeto** [comment]
Thanks, Boris! I've added you as a collaborator, which I should have done long ago, and I'll leave it to your discretion. Alternatively I could archive my pdjson and point to your fork as the "official" one. For me personally, I've outgrown this library, so I'm unlikely to ever use it again, let alone spend time maintaining it.

**Comment by boris-kolpackov** [comment]
Thanks! I am happy to continue applying fixes in your repository. I need JSON5 support so I may also outgrow this pretty soon.

**Comment by boris-kolpackov** [comment]
Fixed in https://github.com/skeeto/pdjson/commit/78fe04b820dc8817f540bdd87fb22887e0ef3981

**Comment by skeeto** [comment]
Thanks!

**Comment by boris-kolpackov** [comment]
@skeeto says:

> Alternatively I could archive my pdjson and point to your fork as the "official" one.

@boris-kolpackov says:

> I need JSON5 support so I may also outgrow this pretty soon.

Ok, I've finally done that. Specifically, I've forked `pdjson` and added support for JSON5 plus a few other changes and improvements (described in the updated README): https://github.com/boris-kolpackov/libpdjson5

Just FYI & FWIW, no expectations.
